### PR TITLE
Capture Villagers, Endermen, Wardens, plus various bug fixes

### LINKED ISSUE #29: Endermen cannot be captured
## Description (Required)
Endermen cannot be captured with the launcher.

## Steps to reproduce the Issue (Required)
Attempt to capture an Enderman. It dodges the projectile and remains uncaptured.

## Expected behavior (Required)
I expected to be able to capture all types of mobs with the launcher.

Since there is no egg for Endermen, I assume this is intentional, but special behavior may be needed to ensure the Enderman does not dodge the projectile.

### LINKED ISSUE #30: Bosses cannot be captured
Withers, Wardens, and Ender Dragons cannot be captured with the launcher.

I assume this is intentional, but I think that all mobs should have capturing code in place, and the ability to capture these mobs should be simply disabled by default.

### LINKED ISSUE #31: Villagers and Wandering Traders cannot be captured
Villagers cannot be captured with the launcher.

This is significant, as they are one of the most important and frustrating mobs to transport around the player's world.

This will require an adapter to ensure their trades, experience, and reputation are retained when captured.

### LINKED ISSUE #32: Captured Zombie Villagers do not retain trades
When capturing a Zombie Villager, the villager is reset to Novice and loses any trades it previously had.

### LINKED ISSUE #33: Spawned mobs placed inside walls
Expected behavior: Placing a mob in an egg on a block should place the mob centered on that block.

Actual behavior: Placing the mob in an egg on a block spawns the mob at the corner of that block. This regularly causes the mob to suffocate when attempting to place them inside confined spaces.

### LINKED ISSUE #34: Inconsistency in mob egg stacking
Reproduction:

- Capture some wild sheep. Note that the eggs do not stack.
- Place the sheep and breed them. Note that the eggs from the bred sheep DO stack.

I have diagnosed that this is due to the that fact that the floating value "Random spawn bonus" is stored on mob eggs from wild entities, when it does not exist on bred mobs.

This could be fixed by excluding the attribute when capturing mobs.

### PR DESCRIPTION
**Pull request by EliteMasterEric**
# Changelog
## Added
- Added new mob eggs:
    - Enderman (resolves #29)
    - Villager (resolves #31)
    - Wandering Trader (resolves #31)
    - Warden (disabled by the default config) (resolves #30)
    - Wither (disabled by the default config) (resolves #30)
- Enderman mob eggs store the Enderman's held block.
- Villager mob eggs store the Villager's type/biome and profession, trades, level, and gossip
- Wandering Trader mob eggs store the Villager's trades.
- Warden mob eggs store the Warden's anger against players.
- Wither mob eggs store the Wither's starting invulnerability ticks.
- Added new config option: `ignored-mob-types`
    - This option allows filtering which mobs can be captured based on type. For example, `entity.minecraft.wither` disables capturing Withers.
    - This resolves an issue where mobs which have been renamed could be captured, even if the base mob's name is ignored.
- Added a note which displays in the Slimefun Guide to indicate whether a mob type cannot be captured.
- Added new config option: `strip-redundant-data`
    - This removes the "Random spawn bonus" from the saved mob data, meaning it is much more likely that eggs will stack in a consistent way. This resolves #34.
## Changed
- Mob capture pellets and mob eggs are no longer consumed when the player is in Creative mode.
- Renamed config option: `ignored-mobs` -> `ignored-mob-names`
    - This option still has its previous behavior, of disabling catching mobs of certain names.
- Zombie Villager mob eggs now store the captured villager's type/biome and profession, as well as their trades. Resolves #32.
    - Zombie Villager mob eggs now display the captured villager's type/biome and profession.
## Fixed
- Entities are now placed centered on the block clicked. This prevents suffocation when spawning in small spaces. Resolves #33.

## TODO

- More testing of the NBT capture functionality needs to be done on older Spigot versions, before 1.19.4.

### CODE REVIEW

**Comment by JustAHuman-xD** [comment]
Introducing nms into an addon simply through a pull request is probably not a good idea and atm I cannot see why it's even necessary.

**Comment by JustAHuman-xD** [comment]
Also renaming a config options name will break existing servers

**Comment by JustAHuman-xD** [comment]
Also for ignored mob types I would suggest naming it "disabled mobs" and just use the entity type enum. No need for the fully "minecraft.entity.x"

**Comment by ybw0014** [comment]
Not gonna touch any nms, it would be pain to maintain. Please submit PRs separately for each issue.

**Pull request closed without merging**
